# Generated by Django 4.0.4 on 2022-06-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la marca')),
                ('nombre_marca', models.CharField(max_length=50, verbose_name='Nombre de la marca')),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id_modelo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del modelo')),
                ('nombre_modelo', models.CharField(max_length=50, verbose_name='Nombre del modelo')),
                ('IdMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.marca')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la region')),
                ('nombre_region', models.CharField(max_length=30, verbose_name='Nombre de la region')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del rol')),
                ('nombre_rol', models.CharField(max_length=10, verbose_name='Nombre del rol')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del status')),
                ('nombre_status', models.CharField(max_length=25, verbose_name='Nombre del status')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('rut_o_pasaporte', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Identifiacion de la perrsona')),
                ('contra_cliente', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre de la persona')),
                ('appaterno', models.CharField(max_length=25, verbose_name='apellido paterno de la persona')),
                ('apmaterno', models.CharField(max_length=25, verbose_name='apellido materno de la persona')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento del cliente')),
                ('correo', models.CharField(max_length=100, verbose_name='correo de la persona')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion de la persona')),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente vehiculo')),
                ('nro_chasis', models.CharField(max_length=17, verbose_name='Nro chasis')),
                ('color', models.CharField(max_length=25, verbose_name='Color vehiculo')),
                ('estado', models.CharField(max_length=17, verbose_name='Estado del vehiculo, disponible o no disponible')),
                ('asientos', models.CharField(max_length=10, verbose_name='Numero de asientos del vehiculo')),
                ('kilos', models.CharField(max_length=10, verbose_name='Kilos del vehiculo')),
                ('nro_motor', models.CharField(max_length=10, verbose_name='Numero del motor del vehiculo')),
                ('precio_vehiculo', models.IntegerField(verbose_name='Precio del vehiculo')),
                ('rendimiento', models.CharField(max_length=25, verbose_name='rendimiento del vehiculo en kms')),
                ('motor', models.CharField(max_length=10, verbose_name='lts motor y caballos de fuerza')),
                ('descripcion', models.TextField(verbose_name='descripcion del vehiculo')),
                ('imagen1', models.ImageField(upload_to='vehiculos')),
                ('imagen2', models.ImageField(upload_to='vehiculos')),
                ('imagen3', models.ImageField(upload_to='vehiculos')),
                ('idModelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Autoincrementable de la orden')),
                ('dia_reserva', models.DateField(verbose_name='El dia en el que se hizo la reserva')),
                ('dia_inicio', models.DateField(verbose_name='Dia de inicio de el arriendo')),
                ('dia_termino', models.DateField(verbose_name='Dia de termino de el arriendo')),
                ('nro_documento', models.IntegerField(verbose_name='Nro de identificacion')),
                ('precio_total_orden', models.IntegerField(verbose_name='Precio total de la orden')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.status')),
                ('ptente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.vehiculo')),
                ('rutPasaporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la comuna')),
                ('nombre_comuna', models.CharField(max_length=30, verbose_name='Nombre de la comuna')),
                ('idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentCar.region')),
            ],
        ),
    ]
